name: Daily Meeting Reminder

on:
  schedule:
    # Corre todos os dias às 08:00 UTC (que corresponde às 09:00 em Portugal Continental durante o horário de verão e 08:00 no horário de inverno)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  send_reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to send reminders
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
        run: python send_reminders.py
